spring:
  profiles:
    active: local
  sql:
    init:
      platform: mariadb
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3306/DeliveryOrder?serverTimezone=KST&createDatabaseIfNotExist=false&autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        default_batch_fetch_size: 50
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
